# Generated by Django 5.0.7 on 2024-08-07 12:44

import adminpanal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanal', '0009_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=adminpanal.models.upload_to_station)),
                ('name', models.TextField(max_length=256)),
                ('duration', models.FloatField()),
                ('priority', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StationFile', to='adminpanal.station')),
            ],
        ),
    ]
