# Generated by Django 5.0.7 on 2024-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.CharField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
