# Generated by Django 5.0.7 on 2024-10-21 11:40

import adminpanal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=254)),
                ('ip', models.CharField(max_length=254)),
                ('port', models.CharField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FusionFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/Fusions/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('centralArea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='centralAreaGov', to='adminpanal.centralarea')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('long', models.CharField(max_length=256)),
                ('lat', models.CharField(max_length=256)),
                ('fusion_ip', models.CharField(max_length=256)),
                ('fusion_port', models.CharField(max_length=256)),
                ('last_connection', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('central_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationCenArea', to='adminpanal.centralarea')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationGov', to='adminpanal.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationPump', to='adminpanal.station')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_id', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('c', 'Created'), ('off', 'Offline'), ('on', 'Online')], max_length=50)),
                ('last_connection', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosPump', to='adminpanal.pump')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosStation', to='adminpanal.station')),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='NozzleProduct', to='adminpanal.product')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pumpNozzle', to='adminpanal.pump')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationNozzle', to='adminpanal.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=adminpanal.models.upload_to_station)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stationfiles', to='adminpanal.station')),
            ],
        ),
    ]
