# Generated by Django 5.0.7 on 2024-07-28 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0002_centralarea_governorate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='nozzles',
        ),
        migrations.RemoveField(
            model_name='station',
            name='pumps',
        ),
        migrations.AddField(
            model_name='nozzle',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pumpNozzle', to='adminpanal.pump'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzle',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationNozzle', to='adminpanal.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pump',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationPump', to='adminpanal.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='NozzleProduct', to='adminpanal.product'),
        ),
        migrations.DeleteModel(
            name='AdsFile',
        ),
    ]
