# Generated by Django 5.0.7 on 2024-07-28 06:17

import adminpanal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0003_remove_pump_nozzles_remove_station_pumps_nozzle_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='central_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationCenArea', to='adminpanal.centralarea'),
        ),
        migrations.AlterField(
            model_name='station',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stationGov', to='adminpanal.governorate'),
        ),
        migrations.CreateModel(
            name='StationFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=adminpanal.models.upload_to_station)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stationfiles', to='adminpanal.station')),
            ],
        ),
    ]
