# Generated by Django 5.0.7 on 2024-07-29 11:23

import adminpanal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0005_fusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=adminpanal.models.upload_to_station)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fusionfiles', to='adminpanal.fusion')),
            ],
        ),
    ]
