# Generated by Django 5.0.7 on 2024-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0006_fusionfilehandler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fusionfilehandler',
            name='fusion',
        ),
        migrations.AlterField(
            model_name='fusionfilehandler',
            name='file',
            field=models.FileField(upload_to='files/Fusions/'),
        ),
    ]
