# Generated by Django 5.0.7 on 2024-07-30 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0007_remove_fusionfilehandler_fusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=13.75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='last_connection',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 14, 35, 29, 670842)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('off', 'Offline'), ('on', 'Online')], default='c', max_length=50),
            preserve_default=False,
        ),
    ]
